version: '3.4'

services:
  proxy:
    build:
      context: .
      dockerfile: proxy.dockerfile
    environment:
      CERTBOT_EMAIL: "certbot@example.com"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webui

  webui:
    build:
      context: src/
      dockerfile: Template.Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    restart: always
    expose:
      - "80"
