version: '3.7'

services:
  proxy:
    build:
      context: ./proxy/
      dockerfile: Dockerfile
    environment:
      CERTBOT_EMAIL: "certbot@example.com"
    volumes:
      - letsencrypt:/etc/letsencrypt/live
    restart: always
    ports:
      - "80:80"
      - "443:443"

  webui:
    build:
      context: ../../
      dockerfile: src/VueTemplate.Web/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: "Production"
      DOTNET_URLS: "http://+:80"
    restart: always
    expose:
      - "80"

volumes:
  letsencrypt:
